# ruff: noqa: I001, UP035, F401, PLC0414
from __future__ import annotations

import contextlib as contextlib
import fcntl as fcntl
import hashlib as hashlib
import importlib as importlib
import json as json
import math as math
import os as os
import re as re
import shlex as shlex
import shutil as shutil
import socket as socket
import subprocess as subprocess
import tempfile as tempfile
import time as time
from contextlib import contextmanager as contextmanager
from datetime import UTC as UTC, datetime as datetime, timezone as timezone
from functools import lru_cache as lru_cache
from pathlib import Path as Path
from statistics import median as median
from typing import Any as Any, Callable as Callable, Iterable as Iterable, Iterator as Iterator, Mapping as Mapping, Sequence as Sequence

from reckon import ledger as ledger, review_tiers as review_tiers
from reckon._timestamps import parse_utc as parse_utc
from reckon.capabilities import _charged_input_from_usage as _charged_input_from_usage
from reckon.crew import lane_document as _lane_document
from reckon.crew import metering as metering, plan_review as plan_review, quota_weight as quota_weight, runs as runs
from reckon.crew import repair as repair_module
from reckon.crew import review as review_module
from reckon.crew import review_need as review_need
from reckon.crew.host_lease import LEASE_RENEW_SECONDS as LEASE_RENEW_SECONDS
from reckon.crew.node import (
    _TERMINAL_RUN_PHASES as _TERMINAL_RUN_PHASES,
    DEFAULT_WATCH_STALL_WINDOW as DEFAULT_WATCH_STALL_WINDOW,
    INTERRUPTED_RUN_PHASE as INTERRUPTED_RUN_PHASE,
    LOG_STALE_AFTER_SECONDS as LOG_STALE_AFTER_SECONDS,
    CrewError as CrewError,
    parse_duration as parse_duration,
)
from reckon.crew.reports import (
    NON_TERMINAL_MANIFEST_STATUSES as NON_TERMINAL_MANIFEST_STATUSES,
    TERMINAL_MANIFEST_STATUSES as TERMINAL_MANIFEST_STATUSES,
    ManifestParseError as ManifestParseError,
    manifest_status_is_template as manifest_status_is_template,
    parse_manifest as parse_manifest,
)
from reckon.crew.routing import _signal_process_group as _signal_process_group
from reckon.crew.runs import (
    _manifest_freshness as _manifest_freshness,
    _mutate_pointer as _mutate_pointer,
    _process_start_time as _process_start_time,
    _project_watch_claim as _project_watch_claim,
    _read_watch_record as _read_watch_record,
    _stream_quiet_seconds as _stream_quiet_seconds,
    _utc_now as _utc_now,
    _write_watch_record as _write_watch_record,
    list_live as list_live,
    producer_lease_seconds as producer_lease_seconds,
    read_pointer as read_pointer,
    update_watch_registration as update_watch_registration,
    watch_lease_renewed_at as watch_lease_renewed_at,
    watch_lock_path as watch_lock_path,
)
from reckon.crew.ticker import NEEDS_ACTION as NEEDS_ACTION, Ticker as Ticker, _agent_label as _agent_label

from .recovery_vocabulary import (
    ACTIONABLE_RECOVERY_CLASSIFICATIONS as ACTIONABLE_RECOVERY_CLASSIFICATIONS,
    LAUNCH_WINDOW_SECONDS as LAUNCH_WINDOW_SECONDS,
    MANIFEST_REWRITE_WINDOW_SECONDS as MANIFEST_REWRITE_WINDOW_SECONDS,
    PLAN_REVIEW_NODE_PREFIX as PLAN_REVIEW_NODE_PREFIX,
    RECOVERY_CLASSES as RECOVERY_CLASSES,
    RECOVERY_CLASSIFICATIONS as RECOVERY_CLASSIFICATIONS,
    RECOVERY_VERBS as RECOVERY_VERBS,
    RESUMPTION_READING_CLASSIFICATIONS as RESUMPTION_READING_CLASSIFICATIONS,
    REVIEW_NODE_PREFIX as REVIEW_NODE_PREFIX,
    REVIEW_ROLE as REVIEW_ROLE,
    WAITING_STATUS as WAITING_STATUS,
    WAIT_CONDITION_STATES as WAIT_CONDITION_STATES,
    WAIT_PROBE_TIMEOUT_SECONDS as WAIT_PROBE_TIMEOUT_SECONDS,
)
from .recovery_classification import (
    classify_pointer as classify_pointer,
)
from .recovery_liveness import (
    ATTEMPT_RECORD_NAME as ATTEMPT_RECORD_NAME,
    EXIT_RECORD_NAME as EXIT_RECORD_NAME,
    MANIFEST_SIZE_MEMORY_MAX as MANIFEST_SIZE_MEMORY_MAX,
    STRANDED_LAUNCH_BOUND_SECONDS as STRANDED_LAUNCH_BOUND_SECONDS,
    WORKER_RECORD_NAME as WORKER_RECORD_NAME,
    _MANIFEST_SIZES_READ as _MANIFEST_SIZES_READ,
    _PRE_SPAWN_PHASES as _PRE_SPAWN_PHASES,
    _absence_of_a_verdict_is_transient as _absence_of_a_verdict_is_transient,
    _attempt_started_seconds as _attempt_started_seconds,
    _carries_orientation_write as _carries_orientation_write,
    _declared_wait_age_seconds as _declared_wait_age_seconds,
    _exit_record_end_phrase as _exit_record_end_phrase,
    _exit_record_is_launch_failure as _exit_record_is_launch_failure,
    _int_or_none as _int_or_none,
    _interruption_evidence as _interruption_evidence,
    _launched_on_this_host as _launched_on_this_host,
    _live_descendant as _live_descendant,
    _manifest_may_be_mid_rewrite as _manifest_may_be_mid_rewrite,
    _manifest_size_key as _manifest_size_key,
    _manifest_wait as _manifest_wait,
    _observed_phase as _observed_phase,
    _orientation_write_of_a_run_in_motion as _orientation_write_of_a_run_in_motion,
    _process_children as _process_children,
    _process_reading as _process_reading,
    _reading_host as _reading_host,
    _record_is_known_foreign as _record_is_known_foreign,
    _record_newest_stream as _record_newest_stream,
    _remember_manifest_size as _remember_manifest_size,
    _run_chain_manifest_freshness as _run_chain_manifest_freshness,
    _run_exit_record as _run_exit_record,
    _run_stream_mtime as _run_stream_mtime,
    _run_stream_quiet_seconds as _run_stream_quiet_seconds,
    _seconds_since_dispatch as _seconds_since_dispatch,
    _stranded_launch as _stranded_launch,
    _within_launch_window as _within_launch_window,
    _worker_launched_after_manifest as _worker_launched_after_manifest,
    _worker_record as _worker_record,
    _worker_record_liveness as _worker_record_liveness,
    _worker_record_pid as _worker_record_pid,
    external_wait as external_wait,
    live_worker_pid as live_worker_pid,
    local_liveness as local_liveness,
    process_alive as process_alive,
)
from .recovery_memo import (
    CLASSIFICATION_MEMO_NAME as CLASSIFICATION_MEMO_NAME,
    CLASSIFICATION_MEMO_VERSION as CLASSIFICATION_MEMO_VERSION,
    LANE_EVENT_WINDOW_SECONDS as LANE_EVENT_WINDOW_SECONDS,
    _ADMISSION_STREAM_BYTES as _ADMISSION_STREAM_BYTES,
    _CLASSIFICATION_MEMO_IN_FLIGHT as _CLASSIFICATION_MEMO_IN_FLIGHT,
    _CLASSIFICATION_RUN_RECORDS as _CLASSIFICATION_RUN_RECORDS,
    _LANE_CAUSE_CLOCK_TIME as _LANE_CAUSE_CLOCK_TIME,
    _LANE_CAUSE_PID as _LANE_CAUSE_PID,
    _LANE_CAUSE_RUN_ID as _LANE_CAUSE_RUN_ID,
    _LANE_CAUSE_TIMESTAMP as _LANE_CAUSE_TIMESTAMP,
    _classification_inputs as _classification_inputs,
    _classification_key as _classification_key,
    _classification_memo_path as _classification_memo_path,
    _count_admission_bytes as _count_admission_bytes,
    _directory_identity as _directory_identity,
    _file_identity as _file_identity,
    _file_inode as _file_inode,
    _git_directory as _git_directory,
    _lane_cause_signature_text as _lane_cause_signature_text,
    _memo_for as _memo_for,
    _memo_published as _memo_published,
    _misfiled_review_candidates as _misfiled_review_candidates,
    _own_review_record_exists as _own_review_record_exists,
    _read_classification_memo as _read_classification_memo,
    _review_input_identities as _review_input_identities,
    _terminal_lane_signal as _terminal_lane_signal,
    _worktree_head_identity as _worktree_head_identity,
    _write_classification_memo as _write_classification_memo,
    group_terminal_lane_events as group_terminal_lane_events,
    take_admission_stream_bytes as take_admission_stream_bytes,
)
from .recovery_repair_dispatch import (
    _RECORD_PATH_PREFIXES as _RECORD_PATH_PREFIXES,
    _config_carrying_suite as _config_carrying_suite,
    _is_record_path as _is_record_path,
    _is_repair_node as _is_repair_node,
    _manifest_reports_round as _manifest_reports_round,
    _opened_repair_rounds as _opened_repair_rounds,
    _promoted_run_ids as _promoted_run_ids,
    _record_repair_dispatch as _record_repair_dispatch,
    _repair_in_flight as _repair_in_flight,
    _repair_launch_refusal as _repair_launch_refusal,
    _repair_resume_advice as _repair_resume_advice,
    _repair_round_started_mtime_ns as _repair_round_started_mtime_ns,
    _repair_source_refusal as _repair_source_refusal,
    _repairable_scope as _repairable_scope,
    _review_carried_head as _review_carried_head,
    _reviewed_run_is_busy as _reviewed_run_is_busy,
    _reviewed_run_refused_the_round as _reviewed_run_refused_the_round,
    _reviewed_run_suite_command as _reviewed_run_suite_command,
    _sweep_review_tier as _sweep_review_tier,
    _sweeping_session as _sweeping_session,
    _within_fence as _within_fence,
    dispatch_repair_for_run as dispatch_repair_for_run,
)
from .recovery_review_acceptance import (
    REVIEW_ACCEPTANCE_FLOOR as REVIEW_ACCEPTANCE_FLOOR,
    _commits_missing_from as _commits_missing_from,
    _recorded_gate_passed as _recorded_gate_passed,
    _review_accepts_promotion as _review_accepts_promotion,
    accept_clean_review as accept_clean_review,
    dispatch_awaiting_reviews as dispatch_awaiting_reviews,
)
from .recovery_review_delivery import (
    DELIVERED_REVIEW_GRACE_SECONDS as DELIVERED_REVIEW_GRACE_SECONDS,
    _complete_manifest_write_time as _complete_manifest_write_time,
    _delivered_review_record as _delivered_review_record,
    _is_review_run as _is_review_run,
    _read_complete_review as _read_complete_review,
    _resolved_reviewed_run_id as _resolved_reviewed_run_id,
    _review_store_record_paths as _review_store_record_paths,
    _stop_delivered_reviews as _stop_delivered_reviews,
    review_delivered as review_delivered,
)
from .recovery_review_dispatch import (
    CARRY_FORWARD_FIELD as CARRY_FORWARD_FIELD,
    IN_HARNESS_LAUNCH as IN_HARNESS_LAUNCH,
    LANE_READING_FRESH_SECONDS as LANE_READING_FRESH_SECONDS,
    REPAIR_ADVICE_SCOPE_LINE as REPAIR_ADVICE_SCOPE_LINE,
    REPAIR_DISPATCH_FIELD as REPAIR_DISPATCH_FIELD,
    REPAIR_RESUME_LIMIT as REPAIR_RESUME_LIMIT,
    REPAIR_ROUNDS_FIELD as REPAIR_ROUNDS_FIELD,
    REPAIR_ROUND_OPENING_STATUSES as REPAIR_ROUND_OPENING_STATUSES,
    REPAIR_ROUND_TOKEN_LINE as REPAIR_ROUND_TOKEN_LINE,
    REPAIR_SOURCE_ROLE as REPAIR_SOURCE_ROLE,
    REVIEW_DISPATCH_FIELD as REVIEW_DISPATCH_FIELD,
    REVIEW_EXCLUDED_BACKENDS_KEY as REVIEW_EXCLUDED_BACKENDS_KEY,
    REVIEW_SETTLE_SECONDS as REVIEW_SETTLE_SECONDS,
    _REVIEW_HEAD_PATTERN as _REVIEW_HEAD_PATTERN,
    _changed_paths_between as _changed_paths_between,
    _current_lane_reading as _current_lane_reading,
    _diff_between as _diff_between,
    _discard_composed_plan_review as _discard_composed_plan_review,
    _discard_stranded_review as _discard_stranded_review,
    _dispatch_composed_review as _dispatch_composed_review,
    _failed_review_backend as _failed_review_backend,
    _judge_head_move as _judge_head_move,
    _lane_over_ceiling as _lane_over_ceiling,
    _no_lane_reason as _no_lane_reason,
    _object_id as _object_id,
    _ordered_review_lanes as _ordered_review_lanes,
    _readable_standing_review as _readable_standing_review,
    _record_carried_head as _record_carried_head,
    _record_review_dispatch as _record_review_dispatch,
    _recorded_review_is_live as _recorded_review_is_live,
    _repair_round_token as _repair_round_token,
    _repo_relative_cited_path as _repo_relative_cited_path,
    _resolve_abbreviated_commit as _resolve_abbreviated_commit,
    _resolved_review_config as _resolved_review_config,
    _review_attempt_withdrawn_before_launch as _review_attempt_withdrawn_before_launch,
    _review_backend_excluded as _review_backend_excluded,
    _review_delivered_paths as _review_delivered_paths,
    _review_excluded_backends as _review_excluded_backends,
    _review_head_and_tree as _review_head_and_tree,
    _review_head_covers as _review_head_covers,
    _review_in_flight as _review_in_flight,
    _review_in_harness_backends as _review_in_harness_backends,
    _review_lane_candidates as _review_lane_candidates,
    _review_lane_plan as _review_lane_plan,
    _review_record_subject as _review_record_subject,
    _review_subject as _review_subject,
    _review_worker_launched as _review_worker_launched,
    _run_head_for_review as _run_head_for_review,
    _standing_plan_review as _standing_plan_review,
    _worktree_reclaimed as _worktree_reclaimed,
    carry_review_forward as carry_review_forward,
    dispatch_review_for_run as dispatch_review_for_run,
    review_head_move as review_head_move,
    review_settle_seconds_remaining as review_settle_seconds_remaining,
    withdraw_superseded_review as withdraw_superseded_review,
)
from .recovery_review_subject import (
    _canonical_commits as _canonical_commits,
    _commit_candidates as _commit_candidates,
    _composed_review_lane as _composed_review_lane,
    _is_review_node as _is_review_node,
    _resolve_commit as _resolve_commit,
    _review_dispatch_action as _review_dispatch_action,
    _review_dispatch_argv as _review_dispatch_argv,
    _review_dispatch_fields as _review_dispatch_fields,
    _review_dispatch_tokens as _review_dispatch_tokens,
    _review_is_complete as _review_is_complete,
    _review_lane_hold_action as _review_lane_hold_action,
    _review_tree as _review_tree,
    _reviewed_run_head as _reviewed_run_head,
    _revision_at as _revision_at,
    _stored_review as _stored_review,
    newest_review_for_headless_run as newest_review_for_headless_run,
    plan_review_subject as plan_review_subject,
    review_described_head as review_described_head,
    same_revision as same_revision,
    select_review_for_head as select_review_for_head,
)
from .recovery_stream import (
    DEFAULT_LIFTING_CONDITIONS as DEFAULT_LIFTING_CONDITIONS,
    SELF_LIFTING_RECOVERY_CLASSIFICATIONS as SELF_LIFTING_RECOVERY_CLASSIFICATIONS,
    _BACKGROUND_WAIT_CEILING_RE as _BACKGROUND_WAIT_CEILING_RE,
    _BACKGROUND_WAIT_FINAL_MESSAGE_RE as _BACKGROUND_WAIT_FINAL_MESSAGE_RE,
    _BACKPRESSURE_RETRY_RE as _BACKPRESSURE_RETRY_RE,
    _RATE_LIMIT_RETRY_RE as _RATE_LIMIT_RETRY_RE,
    _SYNTHETIC_MODEL as _SYNTHETIC_MODEL,
    _admission_refusal as _admission_refusal,
    _apply_budget_watchdog as _apply_budget_watchdog,
    _assistant_refusal_text as _assistant_refusal_text,
    _blocked_session_resolution as _blocked_session_resolution,
    _budget_hold_block as _budget_hold_block,
    _budget_overrun_cause as _budget_overrun_cause,
    _budget_timing as _budget_timing,
    _declared_token_budget as _declared_token_budget,
    _generated_tokens as _generated_tokens,
    _harness_command as _harness_command,
    _historical_reference_rate as _historical_reference_rate,
    _observed_stream as _observed_stream,
    _positive_rate as _positive_rate,
    _refusal_block as _refusal_block,
    _result_turned_no_tokens as _result_turned_no_tokens,
    _resume_remedy as _resume_remedy,
    _stream_budget as _stream_budget,
    _stream_completion_stamp as _stream_completion_stamp,
    _stream_exhaustion_block as _stream_exhaustion_block,
    _stream_refusal_block as _stream_refusal_block,
    _stream_retry_block as _stream_retry_block,
    _token_budget_timing as _token_budget_timing,
    manifest_status_is_terminal as manifest_status_is_terminal,
)
from .recovery_wait import (
    RUN_STREAM_GLOBS as RUN_STREAM_GLOBS,
    STREAM_ASSISTANT_RECORD_TYPE as STREAM_ASSISTANT_RECORD_TYPE,
    STREAM_RESULT_RECORD_TYPE as STREAM_RESULT_RECORD_TYPE,
    _BOUNDED_WAIT_TOOL_NAMES as _BOUNDED_WAIT_TOOL_NAMES,
    _PEER_CHANNEL_WAIT_RE as _PEER_CHANNEL_WAIT_RE,
    _SLEEP_RE as _SLEEP_RE,
    _SQUEUE_GUARDED_VAR as _SQUEUE_GUARDED_VAR,
    _STREAM_TAIL_BYTES as _STREAM_TAIL_BYTES,
    _WAIT_ACCEPTED_SHAPES as _WAIT_ACCEPTED_SHAPES,
    _WAIT_BRANCH_STOP as _WAIT_BRANCH_STOP,
    _WAIT_DECLARATION_SCALAR_FIELDS as _WAIT_DECLARATION_SCALAR_FIELDS,
    _WAIT_EXIT_SENTINEL as _WAIT_EXIT_SENTINEL,
    _WAIT_FILE_TEST_COMMANDS as _WAIT_FILE_TEST_COMMANDS,
    _WAIT_HORIZON_FIELDS as _WAIT_HORIZON_FIELDS,
    _WAIT_LIVE_STATE_TOKENS as _WAIT_LIVE_STATE_TOKENS,
    _WAIT_PROBE_COUNT as _WAIT_PROBE_COUNT,
    _WAIT_PROBE_JOB_FLAGS as _WAIT_PROBE_JOB_FLAGS,
    _WAIT_PROBE_NO_OP_COMMANDS as _WAIT_PROBE_NO_OP_COMMANDS,
    _WAIT_PROBE_PID_FLAGS as _WAIT_PROBE_PID_FLAGS,
    _WAIT_PROBE_PORT_COMMANDS as _WAIT_PROBE_PORT_COMMANDS,
    _WAIT_PROBE_PORT_FLAGS as _WAIT_PROBE_PORT_FLAGS,
    _WAIT_PROBE_PORT_RANGE as _WAIT_PROBE_PORT_RANGE,
    _WAIT_PROBE_PRINTER_COMMANDS as _WAIT_PROBE_PRINTER_COMMANDS,
    _WAIT_PROBE_PROCESS_COMMANDS as _WAIT_PROBE_PROCESS_COMMANDS,
    _WAIT_PROBE_SHELL_COMMANDS as _WAIT_PROBE_SHELL_COMMANDS,
    _WAIT_PROBE_SHORT_FLAG as _WAIT_PROBE_SHORT_FLAG,
    _background_wait_signal as _background_wait_signal,
    _emitted_tokens as _emitted_tokens,
    _lane_input_window as _lane_input_window,
    _last_bounded_wait as _last_bounded_wait,
    _last_record_type_in as _last_record_type_in,
    _last_recorded_input_tokens as _last_recorded_input_tokens,
    _newest_stream_last_record_type as _newest_stream_last_record_type,
    _newest_stream_shows_work as _newest_stream_shows_work,
    _probe_live_state_tokens as _probe_live_state_tokens,
    _process_exit_reason as _process_exit_reason,
    _request_input_tokens as _request_input_tokens,
    _run_directory as _run_directory,
    _run_wait_condition_probe as _run_wait_condition_probe,
    _stall_wait_reason as _stall_wait_reason,
    _stream_holds_assistant_record as _stream_holds_assistant_record,
    _unquote_wait_declaration_scalar as _unquote_wait_declaration_scalar,
    _wait_condition_declares_no_wait as _wait_condition_declares_no_wait,
    _wait_condition_observation as _wait_condition_observation,
    _wait_declaration_signature as _wait_declaration_signature,
    _wait_expected_seconds as _wait_expected_seconds,
    _wait_file_condition_observation as _wait_file_condition_observation,
    _wait_file_paths as _wait_file_paths,
    _wait_file_probe as _wait_file_probe,
    _wait_file_shape_refusal as _wait_file_shape_refusal,
    _wait_probe as _wait_probe,
    _wait_probe_cannot_fail as _wait_probe_cannot_fail,
    _wait_probe_is_a_no_op as _wait_probe_is_a_no_op,
    _wait_probe_names_a_count as _wait_probe_names_a_count,
    _wait_probe_names_a_port as _wait_probe_names_a_port,
    _wait_probe_names_an_operand as _wait_probe_names_an_operand,
    _wait_probe_reference_kind as _wait_probe_reference_kind,
    _wait_probe_shape_refusal as _wait_probe_shape_refusal,
    _wait_probe_shell_words as _wait_probe_shell_words,
    _wait_terminal_names_a_live_state as _wait_terminal_names_a_live_state,
    _wait_terminal_names_no_probe_state as _wait_terminal_names_no_probe_state,
    _wait_terminal_values as _wait_terminal_values,
    newest_stream as newest_stream,
    resume_window_refusal as resume_window_refusal,
    stream_paths_newest_first as stream_paths_newest_first,
)
from .recovery_watch import (
    EXPLAINED_STATES as EXPLAINED_STATES,
    FLEET_BLOCKED_STATES as FLEET_BLOCKED_STATES,
    FLEET_SETTLED_STATES as FLEET_SETTLED_STATES,
    FLEET_UNPROMOTED_STATES as FLEET_UNPROMOTED_STATES,
    FLEET_WAITING_STATES as FLEET_WAITING_STATES,
    FLEET_WORKING_STATES as FLEET_WORKING_STATES,
    IDLE_POLL_INTERVAL_CAP_SECONDS as IDLE_POLL_INTERVAL_CAP_SECONDS,
    UNWATCH_SEAT_WAIT_SECONDS as UNWATCH_SEAT_WAIT_SECONDS,
    WAITING_STATES as WAITING_STATES,
    _COMMITS_BEYOND_BASE_CACHE as _COMMITS_BEYOND_BASE_CACHE,
    _COMMITS_BEYOND_BASE_CACHE_LIMIT as _COMMITS_BEYOND_BASE_CACHE_LIMIT,
    _LedgerRunWordReader as _LedgerRunWordReader,
    _SNAPSHOT_CACHE as _SNAPSHOT_CACHE,
    _SNAPSHOT_CACHE_LIMIT as _SNAPSHOT_CACHE_LIMIT,
    _commits_beyond_base as _commits_beyond_base,
    _compute_watch_snapshot as _compute_watch_snapshot,
    _departure_recorded_run_ids as _departure_recorded_run_ids,
    _departure_word as _departure_word,
    _derive_missing_manifest as _derive_missing_manifest,
    _derived_manifest_text as _derived_manifest_text,
    _discard_recorded as _discard_recorded,
    _evict_gone_worktrees as _evict_gone_worktrees,
    _fleet_counts as _fleet_counts,
    _fresh_liveness as _fresh_liveness,
    _generation_rate as _generation_rate,
    _ledger_run_id_reader as _ledger_run_id_reader,
    _manifest_rewritten as _manifest_rewritten,
    _notional_cost as _notional_cost,
    _partition_session_rows as _partition_session_rows,
    _pointer_role as _pointer_role,
    _promote_record_holds as _promote_record_holds,
    _quiet_clock_latest as _quiet_clock_latest,
    _recorded_pointer_word as _recorded_pointer_word,
    _recorded_transition_spend as _recorded_transition_spend,
    _recreate_unlinked_registration as _recreate_unlinked_registration,
    _refresh_snapshot as _refresh_snapshot,
    _refuse_unresolvable_watch as _refuse_unresolvable_watch,
    _remember_commits as _remember_commits,
    _remember_snapshot as _remember_snapshot,
    _scoped_watch_event as _scoped_watch_event,
    _snapshot_reuse_key as _snapshot_reuse_key,
    _spend_facts as _spend_facts,
    _stall_reading as _stall_reading,
    _stall_window_seconds as _stall_window_seconds,
    _utc_seconds as _utc_seconds,
    _watch_registration as _watch_registration,
    _watch_snapshot as _watch_snapshot,
    _watch_transition as _watch_transition,
    _watch_verdict as _watch_verdict,
    _worktree_diff_paths as _worktree_diff_paths,
    agent_label as agent_label,
    closure_disposition_valid as closure_disposition_valid,
    fleet_transitions as fleet_transitions,
    format_watch_transition as format_watch_transition,
    overdue_unreconciled_runs as overdue_unreconciled_runs,
    recover as recover,
    unwatch as unwatch,
    watch_follow as watch_follow,
    watch_ticker as watch_ticker,
)
